/// Flutter icons MyFlutterApp
/// Copyright (C) 2025 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CompressoIcons
///      fonts:
///       - asset: fonts/CompressoIcons.ttf
///
///
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class CompressoIcons {
  CompressoIcons._();

  static const _kFontFam = 'CompressoIcons';
  static const String? _kFontPkg = null;

  static const IconData compress =
      IconData(0xf066, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData compress_alt =
      IconData(0xf422, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData compress_arrows_alt =
      IconData(0xf78c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
